#!/usr/bin/env sh

# Taken from https://github.com/exaco/laravel-octane-dockerfile

set -e

container_mode=${CONTAINER_MODE:-"server"}
run_migrations_and_seeders=${RUN_MIGRATIONS_AND_SEEDERS:-"false"}

echo "Container mode: $container_mode"

init() {
    php artisan optimize:clear; \
    php artisan event:cache; \
    php artisan config:cache; \
    php artisan route:cache;

    if [ ${run_migrations_and_seeders} = "true" ]; then
        echo "Running migrations and seeding database..."
        php artisan migrate --isolated --seed --force;
    fi
}

if [ "$1" != "" ]; then
    exec "$@"
elif [ ${container_mode} = "server" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.server.conf
elif [ ${container_mode} = "reverb" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.reverb.conf
elif [ ${container_mode} = "scheduler" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.scheduler.conf
elif [ ${container_mode} = "queue-worker" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.queue-worker.conf
elif [ ${container_mode} = "worker" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.worker.conf
else
    echo "Container mode mismatched."
    exit 1
fi
